// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnMuhasebe.Persistence.Context;

#nullable disable

namespace OnMuhasebe.Persistence.Migrations
{
    [DbContext(typeof(OnMuhasebePsqlDbContext))]
    [Migration("20240608221420_mig_voucher_edit")]
    partial class mig_voucher_edit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnMuhasebe.Domain.Models.BaseModels.BaseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Decription")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Bank", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AuthName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AuthPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IbanNo")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.BankMotion", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankMotionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasIndex("BankId");

                    b.HasIndex("CustomerId");

                    b.ToTable("BankMotions");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Customer", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("AuthName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CustomerGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("DiscountRatio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("District")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InvoiceTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RiskLimit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasIndex("CustomerGroupId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.CustomerGroup", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("CustomerGroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("CustomerGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e767d4b3-88f7-4af6-932d-431bbfd95c3f"),
                            CreateDate = new DateTime(2024, 6, 8, 22, 14, 20, 525, DateTimeKind.Utc).AddTicks(1151),
                            CreatedUser = "Admin",
                            IsDeleted = false,
                            CustomerGroupName = "Grupsuz"
                        });
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.CustomerUnderGroup", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<Guid>("CustomerGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerUnderGroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CustomerGroupId");

                    b.ToTable("CustomerUnderGroups");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Discount", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<decimal>("DiscountRatio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("ProductId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Employee", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IdentityNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsWork")
                        .HasColumnType("boolean");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("MonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("PrimRatio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TaskNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaskOffice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("WorkOutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WorkStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.EmployeeMotion", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Period")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrimRatio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeMotions");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.FastSale", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<Guid>("FastSaleGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasIndex("FastSaleGroupId");

                    b.HasIndex("ProductId");

                    b.ToTable("FastSales");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.FastSaleGroup", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable("FastSaleGroups");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Kdv", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("KdvName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("KdvRatio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.ToTable("Kdvs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9fd0162-8f72-4d24-accc-1b0c1ec494b4"),
                            CreateDate = new DateTime(2024, 6, 8, 22, 14, 20, 525, DateTimeKind.Utc).AddTicks(1229),
                            CreatedUser = "Admin",
                            IsDeleted = false,
                            KdvName = "%18",
                            KdvRatio = 18m
                        },
                        new
                        {
                            Id = new Guid("0924a136-4b38-42eb-ad09-7b92f1303b8a"),
                            CreateDate = new DateTime(2024, 6, 8, 22, 14, 20, 525, DateTimeKind.Utc).AddTicks(1238),
                            CreatedUser = "Admin",
                            IsDeleted = false,
                            KdvName = "%20",
                            KdvRatio = 20m
                        },
                        new
                        {
                            Id = new Guid("71cc7301-cae0-4937-a1b3-b7697291a176"),
                            CreateDate = new DateTime(2024, 6, 8, 22, 14, 20, 525, DateTimeKind.Utc).AddTicks(1248),
                            CreatedUser = "Admin",
                            IsDeleted = false,
                            KdvName = "%0",
                            KdvRatio = 0m
                        });
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.PaymentType", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("PaymentTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Price", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KdvId")
                        .HasColumnType("uuid");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasIndex("KdvId");

                    b.HasIndex("ProductId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Product", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("GuaranteePeriod")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<string>("Producer")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductUnderGroupName")
                        .HasColumnType("text");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasIndex("ProductGroupId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.ProductGroup", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("ProductGroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("ProductGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3342d171-222f-48bd-901d-17fb7e48d4eb"),
                            CreateDate = new DateTime(2024, 6, 8, 22, 14, 20, 525, DateTimeKind.Utc).AddTicks(1129),
                            CreatedUser = "Admin",
                            IsDeleted = false,
                            ProductGroupName = "Grupsuz"
                        });
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.ProductMotion", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DiscountRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Kdv")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("KdvId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasIndex("KdvId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ProductMotions");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.ProductUnderGroup", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<Guid>("ProductGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductUnderGroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ProductGroupId");

                    b.ToTable("ProductUnderGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c340b1d5-f2fe-4f0c-9d4f-511f78a8643c"),
                            CreateDate = new DateTime(2024, 6, 8, 22, 14, 20, 525, DateTimeKind.Utc).AddTicks(1170),
                            CreatedUser = "Admin",
                            IsDeleted = false,
                            ProductGroupId = new Guid("3342d171-222f-48bd-901d-17fb7e48d4eb"),
                            ProductUnderGroupName = "Grupsuz"
                        });
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.SafeBox", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("AuthCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SafeBoxCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SafeBoxName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CustomerId");

                    b.ToTable("SafeBoxes");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.SafeBoxMotion", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SafeBoxId")
                        .HasColumnType("uuid");

                    b.Property<string>("SafeBoxMotionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("SafeBoxId");

                    b.ToTable("SafeBoxMotions");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.SpecialCode", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpecialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ProductId");

                    b.ToTable("SpecialCodes");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Unit", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd703370-8093-4aa3-9da6-72a1b4a701a5"),
                            CreateDate = new DateTime(2024, 6, 8, 22, 14, 20, 525, DateTimeKind.Utc).AddTicks(1187),
                            CreatedUser = "Admin",
                            IsDeleted = false,
                            UnitName = "ADET"
                        },
                        new
                        {
                            Id = new Guid("80b9d90c-c1bb-41b5-9ff3-2e0ca28d64fa"),
                            CreateDate = new DateTime(2024, 6, 8, 22, 14, 20, 525, DateTimeKind.Utc).AddTicks(1195),
                            CreatedUser = "Admin",
                            IsDeleted = false,
                            UnitName = "KG"
                        },
                        new
                        {
                            Id = new Guid("b08f5c83-252f-4629-9ec0-65eadfe4c0f1"),
                            CreateDate = new DateTime(2024, 6, 8, 22, 14, 20, 525, DateTimeKind.Utc).AddTicks(1203),
                            CreatedUser = "Admin",
                            IsDeleted = false,
                            UnitName = "Paket"
                        });
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.User", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("822e044b-5656-4b44-ad0f-01d7761e2cbe"),
                            CreateDate = new DateTime(2024, 6, 8, 22, 14, 20, 525, DateTimeKind.Utc).AddTicks(1065),
                            CreatedUser = "Admin",
                            IsDeleted = false,
                            Email = "icb1742@gmail.com",
                            FirstName = "Süper",
                            IsActive = true,
                            LastName = "Admin",
                            Password = "17421742"
                        },
                        new
                        {
                            Id = new Guid("c326ee05-4878-4219-958d-ad3caefa4e11"),
                            CreateDate = new DateTime(2024, 6, 8, 22, 14, 20, 525, DateTimeKind.Utc).AddTicks(1109),
                            CreatedUser = "Admin",
                            IsDeleted = false,
                            Email = "eagledenizcilik@outlook.com.tr",
                            FirstName = "Alican",
                            IsActive = true,
                            LastName = "Kartal",
                            Password = "Eagle0204."
                        });
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Voucher", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Debt")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("DiscountRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Owed")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VoucherType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasIndex("BankId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Warehouse", b =>
                {
                    b.HasBaseType("OnMuhasebe.Domain.Models.BaseModels.BaseModel");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AuthCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AuthName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.BankMotion", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.Bank", "Bank")
                        .WithMany("BankMotions")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Domain.Models.Customer", "Customer")
                        .WithMany("BankMotions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Customer", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.CustomerGroup", "CustomerGroup")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CustomerGroup");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.CustomerUnderGroup", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.CustomerGroup", "CustomerGroup")
                        .WithMany("CustomerUnderGroups")
                        .HasForeignKey("CustomerGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CustomerGroup");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Discount", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.Product", "Product")
                        .WithMany("Discounts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.EmployeeMotion", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.Employee", "Employee")
                        .WithMany("EmployeeMotions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.FastSale", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.FastSaleGroup", "FastSaleGroup")
                        .WithMany("FastSales")
                        .HasForeignKey("FastSaleGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Domain.Models.Product", "Product")
                        .WithMany("FastSales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FastSaleGroup");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Price", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.Kdv", "Kdv")
                        .WithMany("Prices")
                        .HasForeignKey("KdvId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Domain.Models.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Kdv");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Product", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.ProductGroup", "ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Domain.Models.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductGroup");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.ProductMotion", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.Kdv", null)
                        .WithMany("ProductMotions")
                        .HasForeignKey("KdvId");

                    b.HasOne("OnMuhasebe.Domain.Models.Product", "Product")
                        .WithMany("ProductMotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("ProductMotions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.ProductUnderGroup", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.ProductGroup", "ProductGroup")
                        .WithMany("ProductUnderGroups")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductGroup");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.SafeBox", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.Customer", null)
                        .WithMany("SafeBoxes")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.SafeBoxMotion", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.Customer", "Customer")
                        .WithMany("SafeBoxMotions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Domain.Models.PaymentType", "PaymentType")
                        .WithMany("SafeBoxMotions")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Domain.Models.SafeBox", "SafeBox")
                        .WithMany("SafeBoxMotions")
                        .HasForeignKey("SafeBoxId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PaymentType");

                    b.Navigation("SafeBox");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.SpecialCode", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.Product", "Product")
                        .WithMany("SpecialCodes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Voucher", b =>
                {
                    b.HasOne("OnMuhasebe.Domain.Models.Bank", null)
                        .WithMany("Vouchers")
                        .HasForeignKey("BankId");

                    b.HasOne("OnMuhasebe.Domain.Models.Customer", "Customer")
                        .WithMany("Vouchers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnMuhasebe.Domain.Models.Employee", null)
                        .WithMany("Vouchers")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("OnMuhasebe.Domain.Models.Warehouse", null)
                        .WithMany("Vouchers")
                        .HasForeignKey("WarehouseId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Bank", b =>
                {
                    b.Navigation("BankMotions");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Customer", b =>
                {
                    b.Navigation("BankMotions");

                    b.Navigation("SafeBoxMotions");

                    b.Navigation("SafeBoxes");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.CustomerGroup", b =>
                {
                    b.Navigation("CustomerUnderGroups");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Employee", b =>
                {
                    b.Navigation("EmployeeMotions");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.FastSaleGroup", b =>
                {
                    b.Navigation("FastSales");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Kdv", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("ProductMotions");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.PaymentType", b =>
                {
                    b.Navigation("SafeBoxMotions");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Product", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("FastSales");

                    b.Navigation("Prices");

                    b.Navigation("ProductMotions");

                    b.Navigation("SpecialCodes");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.ProductGroup", b =>
                {
                    b.Navigation("ProductUnderGroups");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.SafeBox", b =>
                {
                    b.Navigation("SafeBoxMotions");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Unit", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnMuhasebe.Domain.Models.Warehouse", b =>
                {
                    b.Navigation("ProductMotions");

                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
